### ISSUE TITLE
Can we support protobuf3?

### ISSUE THREAD

**Issue by MrKingHH** [baidu/brpc-java#100]

**Comment by wenweihu86** [comment]
@MrKingHH Sure! Would you please help contribute it? If not, we can do it.

**Comment by MrKingHH** [comment]
I am very happy to do this.  I will use my spare time to try my best to finish the work.

**Comment by wenweihu86** [comment]
Thanks very much! please commit your codes to proto3 branch.

**Comment by MrKingHH** [comment]
I only changed some files, why there 122 files changed...

**Comment by jovany-wang** [comment]
@wenweihu86  What's the purpose to merge the changes of pb3 to `proto3` branch?

Why not request a PR to master directly?

If there're many changes that we should merge to `proto3` branch, I'd like to split the changes to many small PRs and merge them into master. one by one.

Look forward to your reply.

**Comment by wenweihu86** [comment]
@jovany-wang we need master to be protobuf 2.5, because it is the main stream version in baidu.

**Comment by wenweihu86** [comment]
@MrKingHH I add some comments for you pull request.

**Comment by MrKingHH** [comment]
![image](https://user-images.githubusercontent.com/22386359/63404716-e44bac80-c416-11e9-86c8-41d033ca0c4a.png)
![image](https://user-images.githubusercontent.com/22386359/63404742-fcbbc700-c416-11e9-82c3-2140ffc1adcb.png)
I have set complie jdk version in root pom.xml file. But when i run `mvn test`, the errors above are reported. I cann't figure it out just now. Can u tell me how to slove this problem?
@wenweihu86
Look forward to your reply!

**Comment by wenweihu86** [comment]
@MrKingHH upgrading the jprotobuf will resolve it.

**Comment by wenweihu86** [comment]
master has supported protobuf 3.x
