### ISSUE TITLE
protocol注册bug,重复的prototype不生效

### ISSUE THREAD

**Issue by dhhua** [baidu/brpc-java#105]
![image](https://user-images.githubusercontent.com/10860809/61863146-a33ca700-af01-11e9-9fe8-c31b150e99a3.png)

这段代码有bug，应该用protocolMap判断，protocolFactory全局没有用

**Comment by wenweihu86** [comment]
哦，这里漏掉 protocolFactoryMap.put操作。
多谢指出。
方便的话，帮提交pr fix哈。

**Comment by dhhua** [comment]
已pr
