### ISSUE TITLE
brpc can keep the message order from client?

### ISSUE THREAD

**Issue by MrKingHH** [baidu/brpc-java#112]
Our projocet must keep the message order from client，but i am not sure whether brpc can keep or not. Can u tell me the result? @wenweihu86 
Look forward to your reply.

**Comment by wenweihu86** [comment]
brpc-java does not support ordered message.  you can use message queue to keep the order.

**Comment by MrKingHH** [comment]
Fine, I got it.Thanks a lot!

**Comment by MrKingHH** [comment]
Sorry for reopen this issse,. I'd want to know is there `stream mode` in brpc-java? @wenweihu86 
Look forward to your reply.

**Comment by wenweihu86** [comment]
@MrKingHH the java implementation does not support stream mode currently.

**Comment by MrKingHH** [comment]
ok. Thanks a lot!
