### ISSUE TITLE
系统信息泄露：不完善的Servlet错误处理

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [baidu/brpc-java#121]
https://github.com/baidu/brpc-java/blob/4101fe96028d93c6d8c2f6c5ccfc0dfdd9a525b6/brpc-java-core/src/main/java/com/baidu/brpc/protocol/http/HttpRpcServlet.java#L54
如果Servlet抛出异常，程序未进行捕获，Servlet容器将会把异常信息响应给用户，建议对Throwable异常进行捕获。

**Comment by wenweihu86** [comment]
@QiAnXinCodeSafe 核心业务执行异常捕获了。
