### ISSUE TITLE
资源未释放：同步锁

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [baidu/brpc-java#123]
https://github.com/baidu/brpc-java/blob/4101fe96028d93c6d8c2f6c5ccfc0dfdd9a525b6/brpc-java-core/src/main/java/com/baidu/brpc/server/ChannelManager.java#L77
程序创建或分配同步锁资源后，不进行合理释放，将会降低系统性能甚至可能会导致死锁，建议在finally代码块中调用unlock()方法，可以保证不管是否发生异常，总会释放锁。

**Comment by wenweihu86** [comment]
@QiAnXinCodeSafe 多谢，已修复。
