### ISSUE TITLE
rpc client could work inproperly in multi thread condition

### ISSUE THREAD

**Issue by zhougit86** [baidu/brpc-java#137]
loadAllExtensions function in the ExtensionLoaderManager might cause problem. e.g. 
ThreadA, is loadAllExtensions and loadProtocol , to generate the protocolMap.
But ThreadB, might skip it and execute getProtocol, which will use a empty may and throw exception.

**Comment by wenweihu86** [comment]
@zhougit86 yes, ThreadB should wait ThreadA load extensions success.
Thank you for discovering the problem.
Would you please help fix it?

**Comment by zhougit86** [comment]
Hi I have submited a merge request, please help review and let me know if any problem. thanks!

**Comment by wenweihu86** [comment]
@zhougit86 thank you for you pull request, it has beed merged into master.

**Comment by zhougit86** [comment]
would you please release a new maven version? as I need to use this for on line service, thank you! @wenweihu86
