### ISSUE TITLE
出现 程序包com.baidu.bjf.remoting.protobuf不存在

### ISSUE THREAD

**Issue by wangqifan** [baidu/brpc-java#143]
在idea中可以运行。 mvn package 打包之后 java -jar 运行后出现 程序包com.baidu.bjf.remoting.protobuf不存在

**Comment by wenweihu86** [comment]
@wangqifan 在使用jprotobuf时，api包要加入jprotobuf precompile maven plugin。

**Comment by wangqifan** [comment]
谢谢 问题解决
