### ISSUE TITLE
brpc-java 等于0的字段和数组值不正确

### ISSUE THREAD

**Issue by FancyJan** [baidu/brpc-java#145]
C++ server是brpc的，比如现在server吐了两个字段，int kvalue = 0, repeated int list = [1,2]
对于 Java client 走grpc协议，能正确拿到 kvalue = 0, List<int>list = [1,2]
对于 Java client 用brpc-java客户端，拿到的 kvalue = null, List<int> list = []

弱弱问下是不是我使用方式不对，使用的方式和demo是一致的。
brpc-java版本 2.5.8
jprotobuf版本 2.2.8

**Comment by wenweihu86** [comment]
可能是jprotobuf的问题，尝试用proto原生编译出的类通信看看。

**Comment by FancyJan** [comment]
嗯，我试着把生成的pb类改成https://github.com/baidu/brpc-java/blob/master/brpc-java-examples/brpc-java-core-examples/src/main/java/com/baidu/brpc/example/jprotobuf/EchoRequest.java中的这种方式之后可以拿到list的值了

**Comment by wenweihu86** [comment]
@FancyJan 帮忙在jprotobuf里提个bug哈。
https://github.com/jhunters/jprotobuf

**Comment by FancyJan** [comment]
> 可能是jprotobuf的问题，尝试用proto原生编译出的类通信看看。
举个例子的话
这是demo中给出的代码：
`@ProtobufClass
public class EchoResponse {
    private java.util.List<String> message;
}`
这个方式是可以正确的获得List对象的值的

这是我用jprotobuf生成的代码：
`public class EchoResponse {
@Protobuf(fieldType=FieldType.STRING, order=1, required=false)
    private java.util.List<String> message;
}`
而这个方式不行

**Comment by FancyJan** [comment]
> @FancyJan 帮忙在jprotobuf里提个bug哈。
> https://github.com/jhunters/jprotobuf

嗯 我再确认下去提下bug。

**Comment by FancyJan** [comment]
> > 可能是jprotobuf的问题，尝试用proto原生编译出的类通信看看。
> 
> 举个例子的话
> 这是demo中给出的代码：
> `@ProtobufClass public class EchoResponse { private java.util.List<String> message; }`
> 这个方式是可以正确的获得List对象的值的
> 
> 这是我用jprotobuf生成的代码：
> `public class EchoResponse { @Protobuf(fieldType=FieldType.STRING, order=1, required=false) private java.util.List<String> message; }`
> 而这个方式不行

我看demo给出的方法是直接在maven里使用jprotobuf插件的，而我这边是用gradle添加jprotobuf插件，自己去把proto文件转换成java文件的，可能我自己转的时候有配置没有配对可能。

**Comment by wenweihu86** [comment]
> 
我看demo给出的方法是直接在maven里使用jprotobuf插件的，而我这边是用gradle添加jprotobuf插件，自己去把proto文件转换成java文件的，可能我自己转的时候有配置没有配对。
> 
没太明白这句话意思？『自己去把proto文件转换成java文件』

**Comment by FancyJan** [comment]
> > 
> 
> 我看demo给出的方法是直接在maven里使用jprotobuf插件的，而我这边是用gradle添加jprotobuf插件，自己去把proto文件转换成java文件的，可能我自己转的时候有配置没有配对。
> 
> > 
> 
> 没太明白这句话意思？『自己去把proto文件转换成java文件』

`com.baidu.bjf.remoting.protobuf.ProtobufIDLProxy.generateSource(new FileInputStream(sourcePath), new File(targetPath));`
就是把proto写好之后，用这个方法去把proto文件转成一堆java文件，再手动把这些java文件打到项目里面去。

**Comment by wenweihu86** [comment]
@FancyJan 为啥要这么做？

**Comment by FancyJan** [comment]
> @FancyJan 为啥要这么做？

主要是不知道gradle怎么用那个插件去引入proto。。而且之前用grpc客户端的时候这样搞可以，所以先采用这样的方式绕过去了。
然后现在的问题是同样的插件，用maven+plugin的方法产生出来的java类，和我用gradle引入同样的包生成出来的java类的格式不一样，体现在生成的代码里用的是@Protobuf注解（maven+plugin）还是@ProtobufClass注解（gradle+编译脚本）。我感觉可能现在的代码对于用@Protobuf内对于repeated字段的支持有限？

**Comment by FancyJan** [comment]
jprotobuf找了个比较新的版本解决了。。。。。。打扰大佬了。。。

**Comment by FancyJan** [comment]
现在的version是2.1.14，之前的版本是1.11.5
