### ISSUE TITLE
no available instance

### ISSUE THREAD

**Issue by OZC123456789** [baidu/brpc-java#163]
与spring集成时，调用的是c++的服务；注册中心是consul
application.yml:
brpc:
  global:
    naming:
      namingServiceUrl: consul://172.xx.xx.xx:8500
      ignoreFailOfNamingService: false
    client:
      maxTryTimes: 3
      workThreadNum: 1
      ioThreadNum: 1

api接口：
public interface WeixinService {
    @BrpcMeta(serviceName = "service.comm.project.weixin.WeixinService", methodName = "getOpenid")
    OpenidResponse getOpenid(OpenidRequest request);
}

proto文件：
```protobuf
syntax = "proto3";

package service.comm.project.weixin;

option cc_generic_services = true;
option java_generic_services = true;
option py_generic_services = true;
message openidRequest {
    string appid = 1;
}
message openidResponse {
    int32 retcode = 1;
}
service WeixinService {
    rpc getOpenid(openidRequest) returns (openidResponse);
};
```

consul:
![image](https://user-images.githubusercontent.com/37678256/79208961-5c1e8980-7e75-11ea-869c-a63a9952896e.png)

其他的配置没有了，写法参考的是brpc-spring-boot-examples-client，基本一样的结构。

报错：
![image](https://user-images.githubusercontent.com/37678256/79209066-82dcc000-7e75-11ea-8bec-d3280ae82a5a.png)

**Comment by OZC123456789** [comment]
ConsulNamingService 2.5.9
![image](https://user-images.githubusercontent.com/37678256/79707248-6665db00-82ee-11ea-9bd7-734392b7ede8.png)
3.0.0
![image](https://user-images.githubusercontent.com/37678256/79707273-85646d00-82ee-11ea-8254-965afed417c1.png)
好像是因为这个问题，请尽快更新maven版本，谢谢。

**Comment by raptium** [comment]
3.0.0 版本已发布，关闭此 Issue
