### ISSUE TITLE
RpcContext.logId可否从Integer改为Long

### ISSUE THREAD

**Issue by Huang-ShuXing** [baidu/brpc-java#167]
如题

**Comment by raptium** [comment]
我觉得可以改，现在 `Request` 上的 `logId` 就是 `long` 型。
不过需要注意的是，某些使用固定长度 `logId` 字段的协议比如 `NSHead` 可能不支持。
@wenweihu86 看下？

**Comment by wenweihu86** [comment]
可以改成Long的，如果具体协议传输时使用的是int，可能会被截断。
