### ISSUE TITLE
请问example中的async client call为什么是async,最终不是会阻塞当前线程吗?

### ISSUE THREAD

**Issue by ssolid2014** [baidu/brpc-java#179]
Hi, 感谢你们开源了这个代码,我想请教一个问题,example中的RpcClientTest.java里面的async client call的代码,如下

        EchoServiceAsync asyncEchoService = BrpcProxy.getProxy(rpcClient, EchoServiceAsync.class);
        try {
            Future<Echo.EchoResponse> future = asyncEchoService.echo(request, callback);
            try {
                Echo.EchoResponse response = future.get(1000, TimeUnit.MILLISECONDS);
                System.out.println("response from future:" + response.getMessage());
            } catch (Exception ex1) {
                ex1.printStackTrace();
            }
        } catch (RpcException ex) {
            System.out.println("rpc send failed, ex=" + ex.getMessage());
        }

按我理解,这里的 future.get(1000, TimeUnit.MILLISECONDS); 实际上是会阻塞当前线程的吧?
这样的话为什么还是async呢?
然后如果我的server的业务逻辑里面需要调用另一个server的client,然后也是用这种方式的话,那server的业务逻辑所在的线程不是也会被阻塞吗?
还是说我的理解有误?
谢谢.

**Comment by wenweihu86** [comment]
这里只是列举了async的发送和获取结果的使用方法。实际应用可以这样用：并行请求多个服务，然后在顺序调用各个服务返回的future.get()。

**Comment by ssolid2014** [comment]
谢谢你的解答,不过我还是有一点疑问,如果我的业务逻辑是调用A服务,做点处理,再调用B服务,做点处理,再调用C服务,那这整个过程中,处理业务逻辑的进程实际上是无法切换出去处理其他业务逻辑的对么?

**Comment by wenweihu86** [comment]
是的，因为后续的逻辑要依赖每次rpc调用的结果。

**Comment by xiaobinshe** [comment]
thanks.

**Comment by ssolid2014** [comment]
多谢解答.
