### ISSUE TITLE
更新一下二维码吧，想加个群

### ISSUE THREAD

**Issue by liuyueve** [baidu/brpc-java#197]
@raptium

**Comment by gddghs** [comment]
> 
请问你加到了吗？我也想加个群，

**Comment by tullyliu** [comment]
看首页最末位有个管理员微信，加了可以帮忙拉群

**Comment by gddghs** [comment]
这个图片加载不出来了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baidu/brpc-java"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 下午3:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [baidu/brpc-java] 更新一下二维码吧，想加个群 (#197)





 
看首页最末位有个管理员微信，加了可以帮忙拉群

**Comment by liuyueve** [comment]
这个你加到了嘛，没加到可以加我微信

**Comment by gddghs** [comment]
> 没呢，我vx: t_2012byh，麻烦拉我进群咧，谢啦
