### ISSUE TITLE
health检查bug？ 

### ISSUE THREAD

**Issue by sushe2111** [baidu/brpc-java#213]
https://github.com/baidu/brpc-java/blob/8556f7cf2c8e5fcea5151a43c948ad4eda5e3646/brpc-java-governance/src/main/java/com/baidu/brpc/naming/HealthyCheckTimer.java#L66
检查healthInstances队列是否为UnHealth, 是不是应该为if( ！isHealthy) { newUnhealthyInstances.add(instance);}
当前发现healthInstaces与UnhealthInstances不停的切换。 如果下游服务进行灰度上线的话，负载均衡策略是不是就会有问题呢？

**Comment by chestnutWang** [comment]
https://github.com/baidu/brpc-java/blob/8556f7cf2c8e5fcea5151a43c948ad4eda5e3646/brpc-java-governance/src/main/java/com/baidu/brpc/naming/NamingServiceProcessor.java#L164

我也遇到这个问题，还有如果配置的都是健康的节点，这个bug会导致健康的节点都到了UnhealthInstances，然后getinstance会从UnhealthInstances取节点

**Comment by tullyliu** [comment]
3.0.3版本已修复，感谢各位
