### ISSUE TITLE
maven工程依赖parentPOM文件

### ISSUE THREAD

**Issue by lichenglingl** [baidu/brpc-java#22]
MAVEN工程引入brpc-java-spring2.0.2依赖后报错
Failure to find com.baidu:brpc-java-parent:pom:2.0.2
在http://central.maven.org/maven2/com/baidu/ 下仅找到
brpc-java/                                                       -         -      
brpc-java-spring/

**Comment by wenweihu86** [comment]
@lichenglingl brpc-java-spring 2.0.2是存在的呀。brpc-java-naming-zookeeper包含在即将发布的版本中，代码已经测试完成，这两天会发布到maven中央仓库。

**Comment by lichenglingl** [comment]
brpc-java-spring 2.0.2是存在的
问题是独立的MAVEN工程引入brpc-java-spring 2.0.2后，需要下载brpc-java-parent:pom:2.0.2
报错Failure to find com.baidu:brpc-java-parent:pom:2.0.2

**Comment by wenweihu86** [comment]
@lichenglingl 你改成2.2.0应该没问题了。
