### ISSUE TITLE
CompressManager 的单例实现中，构造函数为什么没有采用private ，而是用了protected

### ISSUE THREAD

**Issue by lipeishen** [baidu/brpc-java#38]
![image](https://user-images.githubusercontent.com/6881761/55312942-42dcb200-5499-11e9-96b5-26351b0fb338.png)

**Comment by wenweihu86** [comment]
protected method can be called by extended class

**Comment by jovany-wang** [comment]
I also think it's better to use `private` here since `protected` method can be visible to the package and all subclasses.

@wenweihu86 Or could you please explain a bit more about the reason for using `protected` here?

**Comment by wenweihu86** [comment]
@jovany-wang @lipeishen I use protected at the very start, so application can subclass  CompressManager to implement custom compress type. but I find that it is better to add method addCompress to add custom compress type now, so it may change to private constructor here, sorry.

**Comment by jovany-wang** [comment]
Thanks, I'll refine it later.
