### ISSUE TITLE
brpc-java client能否访问brpc c++ Server ？

### ISSUE THREAD

**Issue by elasticlog** [baidu/brpc-java#55]
rt，我发现brpc-java 的相关协议proto文件和brpc不一样

**Comment by wenweihu86** [comment]
可以访问的，多了extFields用于插入自定义trace字段。

**Comment by qiuhuakang** [comment]
> 可以访问的，多了extFields用于插入自定义trace字段。

可以麻烦问一下，有没有brpc-java client请求brpc c++ Server的例子呀

**Comment by mghio** [comment]
> > 可以访问的，多了extFields用于插入自定义trace字段。
> 
> 可以麻烦问一下，有没有brpc-java client请求brpc c++ Server的例子呀

同问？
