### ISSUE TITLE
ServiceManager find service bug

### ISSUE THREAD

**Issue by JoeCqupt** [baidu/brpc-java#86]
![image](https://user-images.githubusercontent.com/12369652/59734720-190b7e00-9285-11e9-909c-c5a530aff1b0.png)

When using the http json protocol, it doesn't work. Because the service provider's serviceMap key is the service's full path class name and method name, httpRequest only contains the service class name and method name, which causes RpcMethodInfo not found on the service provider side.

**Comment by wenweihu86** [comment]
@JoeCqupt thanks to find this issue. yes, HttpRpcProtocol.encodeRequest has bug, it should use serviceName and methodName of RpcMethodInfo, instead of target method info.
Could you please help fix this issue?

**Comment by JoeCqupt** [comment]
@wenweihu86  ok   i will provide a pull request later
