### ISSUE TITLE
POJO类中boolean类型的变量建议不要以isXXX命名

### ISSUE THREAD

**Issue by fingthinking** [baidu/brpc-java#9]
参考阿里巴巴Java手册：
> POJO 类中布尔类型的变量，都不要加 is，否则部分框架解析会引起序列化错误。 反例:定义为基本数据类型boolean isSuccess;的属性，它的方法也是isSuccess()，RPC 框架在反向解析的时候，“以为”对应的属性名称是 success，导致属性获取不到，进而抛出异常。

虽然下面的这些Case并不需要序列化，但其属性命名存在一定的不规范，如: fromRpcContext与isFromRpcContext属性，使用lombok生成的method，均为`isFromRpcContext()`, 容易产生一定的误导，而Setter方法，则均为`setFromRpcContext(boolean )`

个人建议，如果是类内部属性，不会作为POJO类(即存在Getter, Setter属性)的话，加is, 否则不要加is

https://github.com/baidu/brpc-java/blob/aba698ad4695b350a0fb347da4fe828b5fbb81ea/brpc-java-core/src/main/java/com/baidu/brpc/server/RpcServerOptions.java#L33

https://github.com/baidu/brpc-java/blob/aba698ad4695b350a0fb347da4fe828b5fbb81ea/brpc-java-core/src/main/java/com/baidu/brpc/client/RpcClientOptions.java#L31

https://github.com/baidu/brpc-java/blob/aba698ad4695b350a0fb347da4fe828b5fbb81ea/brpc-java-core/src/main/java/com/baidu/brpc/ChannelInfo.java#L43

**Comment by wenweihu86** [comment]
@fingthinking 多谢给出建议，确实去掉is更好。如果方便的话，可否帮忙提个pull request修复下？

**Comment by wenweihu86** [comment]
已修复。
