### ISSUE TITLE
brpc 2.5.1 Demo cannot run.

### ISSUE THREAD

**Issue by MrKingHH** [baidu/brpc-java#99]
I use protobuf-2.5 to generate ECHO.java file，this process is right. But when i open the RpcClientTest.java and RpcServerTest.java etc. There are many errors in these files. So what's problem with them, and what should i do to solve these problems?
![image](https://user-images.githubusercontent.com/22386359/61017191-da20a200-a3c4-11e9-8a43-0d8db8b38a34.png)

**Comment by wenweihu86** [comment]
@MrKingHH you need to run local_build.sh to generate proto files.

**Comment by MrKingHH** [comment]
ok , i will try it in my linux operating system.  I  used it in windows before.

**Comment by wenweihu86** [comment]
please use mvn clean install -DskipTests under window.

**Comment by MrKingHH** [comment]
![image](https://user-images.githubusercontent.com/22386359/61060877-d70dcc00-a42d-11e9-9106-0728afec3ee3.png)
![image](https://user-images.githubusercontent.com/22386359/61060859-cf4e2780-a42d-11e9-8e4f-8ae51ceddd4a.png)
Build project successfully. But there are still existing some errors. The red sections seem to indicate that there are not these methods in class **RpcClientOptions.**
![image](https://user-images.githubusercontent.com/22386359/61061246-7632c380-a42e-11e9-8166-928d44c8aecc.png)
And i check it out in **RpcClientOptions.java**. There indeed not existing these methods.

**Comment by wenweihu86** [comment]
@MrKingHH you need install Lombok plugin.

**Comment by MrKingHH** [comment]
ok. when i have installed lombok plugin in IDEA, the project can run successfully. Thanks a lot! 
![image](https://user-images.githubusercontent.com/22386359/61128579-d3894c00-a4e4-11e9-9367-c9a8e6b53c51.png)
![image](https://user-images.githubusercontent.com/22386359/61128590-dab05a00-a4e4-11e9-903e-da8f0f1cfdcc.png)
But i think it would be useful to add some more specific informations about how to start this project, and it will be beneficial for brpc-java's better development.
